import { readFileSync } from "fs";
import path from "path";
import robots from "@/app/robots";
import sitemap, {
  revalidate as sitemapRevalidate,
  SITEMAP_REVALIDATE_SECONDS,
  stablePublicSitemapRoutes,
} from "@/app/sitemap";
import { getPublicSitePathUrl } from "@/lib/config/publicSiteUrl";

jest.mock("server-only", () => ({}), { virtual: true });

jest.mock("@/lib/metadata/publicDynamicSitemap", () => ({
  getDynamicPublicSitemapEntries: jest.fn().mockResolvedValue([]),
}));

const readRepoFile = (relativePath: string) =>
  readFileSync(path.join(process.cwd(), relativePath), "utf8");

describe("public metadata and discovery files", () => {
  it("replaces scaffolded root metadata with production-safe archive metadata", () => {
    const layoutSource = readRepoFile("src/app/layout.tsx");

    expect(layoutSource).toContain("Joseph Laoutaris Art Archive");
    expect(layoutSource).toContain("public Joseph Laoutaris art archive");
    expect(layoutSource).toContain("metadataBase: getPublicSiteUrl()");
    expect(layoutSource).toContain("alternates");
    expect(layoutSource).toContain("canonical");
    expect(layoutSource).toContain("openGraph");
    expect(layoutSource).toContain("twitter");
    expect(layoutSource).not.toMatch(/Create Next App/);
    expect(layoutSource).not.toMatch(/Generated by create next app/);
    expect(layoutSource).not.toMatch(
      /checkout|payments?|shipping|refunds?|guarantees?/i
    );
  });

  it("keeps scaffold metadata out of app discovery source", () => {
    const combinedSource = [
      "src/app/layout.tsx",
      "src/app/robots.ts",
      "src/app/sitemap.ts",
      "src/lib/config/publicSiteUrl.ts",
    ]
      .map(readRepoFile)
      .join("\n");

    expect(combinedSource).not.toMatch(/Create Next App/);
    expect(combinedSource).not.toMatch(/Generated by create next app/);
  });

  it("allows public crawling while excluding private and API paths", () => {
    expect(robots()).toEqual({
      rules: {
        userAgent: "*",
        allow: "/",
        disallow: ["/admin", "/account", "/api"],
      },
      sitemap: getPublicSitePathUrl("/sitemap.xml"),
    });
  });

  it("keeps stable public sitemap routes in discovery output", async () => {
    const entries = await sitemap();
    const urls = entries.map(({ url }) => url);

    expect(urls).toEqual(
      stablePublicSitemapRoutes.map(({ path }) => getPublicSitePathUrl(path))
    );
    expect(urls).toEqual(
      expect.arrayContaining([
        getPublicSitePathUrl("/"),
        getPublicSitePathUrl("/artwork"),
        getPublicSitePathUrl("/collections"),
        getPublicSitePathUrl("/biography"),
        getPublicSitePathUrl("/blog"),
        getPublicSitePathUrl("/project/about"),
        getPublicSitePathUrl("/project/contact"),
        getPublicSitePathUrl("/shop/products"),
        getPublicSitePathUrl("/search"),
      ])
    );

    for (const privatePath of ["/admin", "/account", "/api"]) {
      expect(urls).not.toContain(getPublicSitePathUrl(privatePath));
    }

    for (const entry of entries) {
      expect(entry.url).toMatch(/^https:\/\/laoutaris-nextjs\.vercel\.app\//);
      expect(entry.changeFrequency).toEqual(expect.any(String));
      expect(entry.priority).toEqual(expect.any(Number));
    }
  });

  it("makes sitemap freshness source-owned without changing discovery contents", () => {
    expect(SITEMAP_REVALIDATE_SECONDS).toBe(3600);
    expect(sitemapRevalidate).toBe(SITEMAP_REVALIDATE_SECONDS);
  });
});
