import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import React from "react";
import {
  Archivo_Black,
  Cinzel_Decorative,
  Archivo,
  Roboto_Serif,
  Playfair_Display,
  Cormorant,
} from "next/font/google";
import Footer from "@/components/Footer";
import MobileNavLayout from "@/components/ui/header/MobileNavLayout";
import TabletNavLayout from "@/components/ui/header/TabletNavLayout";

const archivoBlack = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-archivo-black",
});

const archivo = Archivo({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  // display: "swap",

  variable: "--font-archivo",
});

const cinzelDecorative = Cinzel_Decorative({
  weight: "400",
  subsets: ["latin"],
  display: "swap",

  variable: "--font-cinzel-decorative",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivoBlack.variable} ${archivo.variable} ${cinzelDecorative.variable}`}
    >
      <body>
        {/* <div className="block sm:hidden">
          <MobileNavLayout />
        </div> */}
        <div className="hidden sm:block">
          <TabletNavLayout />
        </div>
        {/* <Header /> */}
        {children}
        <Footer />
        {/* </Navbar> */}
      </body>
    </html>
  );
}
