import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import React from "react";
import {
  Archivo_Black,
  Cinzel_Decorative,
  Archivo,
  Roboto_Serif,
  Playfair_Display,
  Cormorant,
  Crimson_Text,
} from "next/font/google";
import Footer from "@/components/ui/footer/Footer";

import Header from "@/components/ui/header/Header";

const archivoBlack = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-archivo-black",
});

const archivo = Archivo({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  // display: "swap",

  variable: "--font-archivo",
});

const cinzelDecorative = Cinzel_Decorative({
  weight: "400",
  subsets: ["latin"],
  display: "swap",

  variable: "--font-cinzel-decorative",
});

const crimson = Crimson_Text({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",

  variable: "--font-crimson",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivoBlack.variable} ${archivo.variable} ${cinzelDecorative.variable} ${crimson.variable}`}
    >
      <body>
        <Header />
        <div className="mt-[100px] sm:mt-[180px] md:mt-[230px] lg:mt-[150px] h-[5px] w-full container"></div>

        {children}
        <Footer />
      </body>
    </html>
  );
}
